### ISSUE TITLE
README.md  needs updated instructions to reflect the new location  of the orgInit.sh script

### ISSUE THREAD

**Issue by geoffrothman** [ttse-sfdc/ea-starter-pack#2]
Right now, the instructions show it in the root folder. @ttse-sfdc

**Comment by geoffrothman** [comment]
And actually, if you try to run the orgInit.sh file from the scripts directory, it errors out. So maybe you should move orgInit back to the root :))

**Comment by ttse-sfdc** [comment]
thanks for pointing this out. yes you should run it with `./scripts/orgInit.sh`
